FROM node:16-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm i
COPY . ./
RUN npm run build

FROM node:16-alpine
WORKDIR /app
COPY package*.json ./
RUN npm i --omit=dev --no-audit --no-fund \
    && npm i -g pm2
COPY --from=builder /app/dist ./dist
COPY ./ecosystem.config.js ./

EXPOSE 5000

ENTRYPOINT [ "pm2-runtime", "start", "ecosystem.config.js" ]
